# Generated by Django 3.2 on 2021-04-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brick',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='catalog name')),
                ('color', models.CharField(max_length=7, verbose_name='color')),
                ('type', models.CharField(choices=[(1, 'standard'), (2, 'special')], max_length=8)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
