# Generated by Django 3.2 on 2021-04-12 10:23

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.image_path),
        ),
    ]
