# Generated by Django 3.2 on 2021-04-12 10:36

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_set_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manual',
            name='image',
            field=models.ImageField(null=True, upload_to=catalog.models.image_path),
        ),
    ]
